import type { Metadata } from 'next'
import React from 'react'
import { Theme, Flex, Box, Heading, Container } from '@radix-ui/themes'
import 'normalize.css'
import '@radix-ui/themes/styles.css'
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body>
                <Theme appearance="dark">
                    <Flex direction="column" gap="2">
                        <Box minHeight="screen" style={{ boxSizing: 'border-box' }}>
                            <Container position="sticky">
                                <Flex gap="3" justify="between">
                                    <Box flexGrow="1" py="5">
                                        <Heading size="8" align="center">
                                            Guess Game
                                        </Heading>
                                    </Box>
                                </Flex>
                            </Container>
                            {children}
                        </Box>
                    </Flex>
                </Theme>
            </body>
        </html>
    )
}
